version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Fetching Cache Version
          command: echo $CACHE_VERSION > cache_version
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "cache_version" }}
      - run:
          name: Installing Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          paths:
            - ~/repo
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "cache_version" }}
      - run:
          name: Removing Cache Version file
          command: rm cache_version
      - run:
          name: Testing, Linting, Static Checking and Building
          command: yarn validate
